version: '3'

services:
  rina:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/vendor
    environment:
      FLASK_ENV: development

  redis:
    image: "redis:alpine"
